In [2]:
import pandas as pd
import numpy as np

1. Create a pandas series from each of the items below: a list, numpy and a dictionary

In [9]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

mylist = pd.Series(mylist)
myarr = pd.Series(myarr)
mydict = pd.Series(mydict)

2. Convert the series `ser` into a dataframe with its index as another column on the dataframe.

In [11]:
ser = pd.Series(mydict)
df = ser.to_frame().reset_index()
df.head()

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4

3. Combine ser1 and ser2 to form a dataframe.
4. Give a name to the series ser1 calling it ‘alphabets’.

In [ ]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
combined = pd.concat([ser1, ser2], axis=1)

ser1.name = "alphabets"

5. From ser1 remove items present in ser2.

In [17]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

6. Get all items of ser1 and ser2 not common to both.

In [18]:
ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

7. Compute the minimum, 25th percentile, median, 75th, and maximum of ser.

In [23]:
ser = pd.Series(np.random.normal(10, 5, 25))
np.percentile(ser, q=[0, 25, 50, 75, 100])
# or can use this ser.describe()

array([-2.33671549,  7.59923625, 10.03784102, 12.55530393, 19.99963438])

8. Calculate the frequency counts of each unique value ser.

In [26]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()

f    7
g    6
a    4
e    4
b    3
h    2
d    2
c    2
Name: count, dtype: int64

9. From ser, keep the top 2 most frequent items as it is and replace everything else as '10000'.

In [30]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

print("Top 2 Freq:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = 10000
ser

Top 2 Freq: 3    5
2    3
1    2
4    2
Name: count, dtype: int64

0         3
1         3
2     10000
3         2
4         2
5     10000
6         2
7         3
8         3
9         3
10    10000
11    10000
dtype: int64

10. Reshape the series ser into a dataframe with 7 rows and 5 columns

In [32]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7,5))
df

   0  1  2  3  4
0  8  4  8  3  6
1  7  5  1  8  2
2  2  3  7  3  3
3  2  3  8  9  8
4  7  5  3  9  9
5  9  2  3  4  5
6  4  2  7  5  5